---
title: "Modeling"
author: "Aijin Wang"
date: "4/15/2019"
output: pdf_document
---

```{r prelim, include=FALSE}
# Load packages
pkgs <- c('xtable', 'astsa', 'vars', 'foreign', 'knitr', 'forecast')
lapply(pkgs, library, character.only=T)

# Load data
cols <- c('#000000', '#999999', '#E69F00', '#56B4E9', '#009E73',
          '#FF0000', '#F0E442', '#0072B2', '#D55E00', '#CC79A7')
df <- read.dta('../data/ije-2012-10-0989-File003.dta')

# Cache chunk options
opts_chunk$set(cache=T, autodep=T, cache.comments=F)
```

```{r}
colnames(df) <- c('Date', 'Ozone', 'Temperature', 'Relative Humidity', 'Num Deaths')

# Combine the series into a ts object with appropriate time series labeling
ts_vars <- ts(with(df, cbind(Ozone, Temperature, `Relative Humidity`, `Num Deaths`)), start=c(2002, 1), frequency=365)
```

```{r}
temp1 <- function(vars) {
  temp2 = lapply(df[,2:5], function(x) {
    x <- ts(x, start=c(2002, 1), frequency=365)
    temp <- decompose(x)
    return(temp[[vars]])
  })
  return(temp2)
}

#plot.ts(do.call(cbind, head(temp)))
temp3 <- temp1('seasonal')
plot.ts(do.call(cbind, temp3), main = "Decomposed Seasonality Series for London (2002-2007)")
temp4 = temp1('trend')
plot.ts(do.call(cbind, temp4))
```

```{r}
# nnetar_func <- function(train, test) {
#   attach(as.data.frame(train))
#   temp = Temperature - mean(Temperature)
#   temp2 = temp^2
#   trend = time(temp)
#   fit <- nnetar(`Num Deaths`, p=2, 
#                 xreg=cbind(trend, temp, temp2, `Ozone`,  `Relative Humidity`))
#   detach(as.data.frame(train))
#   
#   attach(as.data.frame(test))
#   # Plot fitted values vs training data
#   plot(train[,'Num Deaths'])
#   lines(ts(fitted(fit), start=c(2002, 1), frequency=365), col='blue')
# 
#   # Plot residuals 
#   plot(resid(fit)); abline(h=0, col='red', lwd=2)
#   qqnorm(resid(fit)); qqline(resid(fit))
#   invisible(acf2(resid(fit)))
# 
#   # Plot forecasts
#   temp = Temperature - mean(Temperature)
#   temp2 = temp^2
#   trend = time(temp)
#   fcast <- forecast(fit, xreg=cbind(trend, temp, temp2, `Ozone`, `Relative Humidity`), PI=T)
#   plot(ts(fcast, start=c(2002, 1), frequency=365))
#   lines(`Num Deaths`, col='red', lty=2)
# 
#   detach(as.data.frame(test))
# }
# 
# # 1 year, 6 month, 3 months
train <- window(ts_vars, start=c(2002, 1), end=c(2005, 365))
test <- window(ts_vars, start=c(2006, 1), end=c(2007, 1))

attach(as.data.frame(train))
temp = train[,'Temperature'] - mean(train[,'Temperature'])
temp2 = temp^2
trend = time(temp)
fit <- nnetar(`Num Deaths`,
              xreg=cbind(trend, temp, temp2, 
                         `Ozone` = train[, 'Ozone'],
                         `Relative Humidity` = train[, 'Relative Humidity']))
detach(as.data.frame(train))

# Plot fitted values vs training data
plot(train[,'Num Deaths'], ylab='Number of Deaths')
lines(ts(fitted(fit), start=c(2002, 1), frequency=365), col='blue')

# Plot residuals 
plot(resid(fit)); abline(h=0, col='red', lwd=2)
qqnorm(resid(fit)); qqline(resid(fit))
invisible(acf2(resid(fit)))

# Plot forecasts
temp = test[,'Temperature'] - mean(test[,'Temperature'])
temp2 = temp^2
trend = time(temp)
fcast <- forecast(fit, xreg=cbind(trend, temp, temp2, `Ozone` = test[, 'Ozone'], `Relative Humidity` = test[, 'Relative Humidity']), PI=T)
#plot(ts_vars[,'Num Deaths'])

fcast$x <- ts(fcast$x, start=c(2002, 1), frequency=365)
fcast$mean = ts(fcast$mean, start=c(2006, 1), frequency=365)
fcast$upper = ts(fcast$upper, start=c(2006, 1), frequency=365)
fcast$lower = ts(fcast$lower, start=c(2006, 1), frequency=365)

plot(train[,"Num Deaths"], xlim = c(2002, 2007))
lines(test[,"Num Deaths"], col = "darkgrey")
lines(fcast$upper[,2], col = "red", lty = 2)
lines(fcast$lower[,2], col = "red", lty = 2)
lines(fcast$mean, col = "red")
```

